### ISSUE TITLE
crash when clicking preferences of magnifier plugin

### ISSUE THREAD

**Issue by jose1711** [raspberrypi-ui/lxpanel-buster#6] opened 2020-12-13 22:58 UTC
This should probably go somewhere else but since I do not see any repository for lxpanel's magnifier plugin I am adding it here. Fresh Raspbian installation:
- right-click upper bar
- choose Panel Settings
- click Panel Applets tab
- scroll down and select Magnifier
- click Preferences

X crashes a result and you'll get a login prompt. `Systemd` logs:
```
Dec 13 23:42:22 raspberrypi polkitd(authority=local)[467]: Unregistered Authentication Agent for unix-session:3 (system bus name :1.27, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Dec 13 23:42:22 raspberrypi lightdm[648]: pam_unix(lightdm-autologin:session): session closed for user pi
Dec 13 23:42:23 raspberrypi systemd-logind[417]: Session 3 logged out. Waiting for processes to exit.
Dec 13 23:42:23 raspberrypi vncserver-x11-serviced[458]: XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
Dec 13 23:42:23 raspberrypi vncserver-x11-serviced[458]:       after 3181 requests (3181 known processed) with 0 events remaining.
Dec 13 23:42:23 raspberrypi vncserver-x11-serviced[458]: XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
Dec 13 23:42:23 raspberrypi vncserver-x11-serviced[458]:       after 2121 requests (2121 known processed) with 0 events remaining.
Dec 13 23:42:23 raspberrypi vncserver-x11-serviced[458]: vncserverui: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
Dec 13 23:42:23 raspberrypi pulseaudio[782]: XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
Dec 13 23:42:23 raspberrypi pulseaudio[782]:       after 17 requests (17 known processed) with 0 events remaining.
Dec 13 23:42:23 raspberrypi bluetoothd[544]: Endpoint unregistered: sender=:1.31 path=/MediaEndpoint/A2DPSource
Dec 13 23:42:23 raspberrypi bluetoothd[544]: Endpoint unregistered: sender=:1.31 path=/MediaEndpoint/A2DPSink
Dec 13 23:42:23 raspberrypi systemd[618]: pulseaudio.service: Main process exited, code=exited, status=1/FAILURE
Dec 13 23:42:23 raspberrypi systemd[618]: pulseaudio.service: Failed with result 'exit-code'.
Dec 13 23:42:23 raspberrypi systemd[618]: pulseaudio.service: Service RestartSec=100ms expired, scheduling restart.
Dec 13 23:42:23 raspberrypi systemd[618]: pulseaudio.service: Scheduled restart job, restart counter is at 1.
Dec 13 23:42:23 raspberrypi systemd[618]: Stopped Sound Service.
Dec 13 23:42:23 raspberrypi systemd[618]: Starting Sound Service...
```

`lxplug-magnifier 0.3`

**Comment by spl237** [comment] 2020-12-13 23:11
Just tried that - works fine for me; no crash; the settings dialog appears as expected.

Do you also get a crash if you right-click the magnifier icon and choose Magnifier Settings? That should open the same dialog box as doing it via the Preferences button.

Are you running this over a virtual desktop session or similar? I can believe that would cause problems with the magnifier.

**Comment by jose1711** [comment] 2020-12-13 23:37
Hmm.. interesting. Actually I don't see any icon on the bar (or any reserved space for it) which is perhaps another weird thing about it. I am using physically connected monitor (via HDMI) with physical keyboard and monitor (VNC server is only running in the background).

**Comment by jose1711** [comment] 2020-12-13 23:50
I installed debugging symbols for `lxpanel` and reran it with `gdb` but I doubt backtrace will be of any use:
```
Thread 1 "lxpanel" received signal SIGTERM, Terminated.
0x7637320c in kill () at ../sysdeps/unix/syscall-template.S:78
78	../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) bt
#0  0x7637320c in kill () at ../sysdeps/unix/syscall-template.S:78
#1  0x766ffe7c in g_closure_invoke () from /usr/lib/arm-linux-gnueabihf/libgobject-2.0.so.0
Backtrace stopped: Cannot access memory at address 0xae
```

**Comment by spl237** [comment] 2020-12-14 08:32
What happens if you open a terminal, pkill lxpanel and then lxpanel -p LXDE-pi; then do the steps that cause the crash - what do you get in the terminal when the crash happens?

**Comment by jose1711** [comment] 2020-12-14 08:35
I only get `Terminated` (and in this case X server continues running)

**Comment by spl237** [comment] 2020-12-14 08:39
Can you open Preferences for any other plugins, such as Ejecter?

Can you try making sure the plugin is installed properly - do sudo apt purge lxplug-magnifier mage, followed by sudo apt install lxplug-magnifier mage?

Also try opening Appearance Settings, going to the Defaults tab and resetting to defaults in case a config file has got corrupted.

**Comment by jose1711** [comment] 2020-12-14 08:48
Tried couple other plugins and opening preferences works fine for them. Unfortunately reinstalling and resetting config file did not help. I will make a reinstall to see if it's possible to reproduce this after first boot.

**Comment by jose1711** [comment] 2020-12-14 09:46
Reinstalled Raspbian 32bit (via NOOBS rescue menu), rebooted, while Raspberry Pi Configuration was running I tried to bring the preferences up and .. got crash again.

**Comment by spl237** [comment] 2020-12-14 09:53
Ah...
Try using Recommended Software to actually install the magnifier (under Universal Access) and then reboot. I wonder if the problem is trying to show a preferences dialog for a plugin which is hidden; the magnifier plugin isn't active unless the magnifier program is installed, which means you can't access the preferences by the usual means (right-clicking the icon) - I think pressing the Preferences button in the place you are pressing it may well cause problems if the plugin hasn't actually loaded.

**Comment by jose1711** [comment] 2020-12-14 10:11
Yup, that did it! Now both icon is shown and preferences work as expected. I'd expect `lxplug-magnifier` to depend on `mage` since without it it's not really usable.

**Comment by spl237** [comment] 2020-12-14 10:17
The trouble is that I wanted to avoid a partially-sighted user having to add a plugin to the taskbar (as that's not a straightforward process), so the way it works is that the plugin is always installed, but is only shown if mage is also installed. This works fine, and makes enabling the magnifier trivial - just install the package using Recommended Software, and it appears on the taskbar with no other configuration required - but it does mean that mage can't be a dependency on lxplug-magnifier, as the plugin is always installed and mage isn't. I'll see if I can do something to disable the preferences dialog in that situation, as it isn't useful without the magnifier installed anyway.

**Comment by jose1711** [comment] 2020-12-14 11:03
Thank you for the explanation. Maybe a virtual package providing both `mage` and `lxplug-magnifier` could help here. But being the first user in years reporting it.. not sure if it's even worth the effort :smile:

**Comment by spl237** [comment] 2020-12-14 19:26
Given the severity of the crash, I thought I really ought to fix this! Now fixed - there'll be a new package in apt in the next day or so. (The fix was pretty trivial - just don't try and close a random PID which ought to have been assigned to the magnifier process, as that isn't going to end well.... ;) )

**Closed by spl237** 2020-12-14 19:26 UTC

**Comment by jose1711** [comment] 2020-12-14 20:01
Wow, thank you for such a quick fix!
